### ISSUE TITLE
broken on raspberry pi 2

### ISSUE THREAD

**Issue by yetzt** [info-beamer/package-shader-example#1] opened 2015-04-13 15:06 UTC
this example does not work as described, it just shows the lua graphic.

raspberry pi 2 with latest raspbian using a 1920×1200 display on hdmi.

**Comment by yetzt** [comment] 2015-04-13 16:07
this seems to be a problem with the localization, when floats are printed with a colon instead of a dot.

**Comment by yetzt** [comment] 2015-04-13 16:14
`LANG=en_EN info-beamer ./package-shader-example` works. please fix.

**Comment by dividuum** [comment] 2015-04-13 16:29
Which info-beamer version? Which locale? Running on Raspbian? Please provide all information that enables me to reproduce this problem. Thanks.

**Comment by yetzt** [comment] 2015-04-13 16:40
i used `0.9.0-beta-pre1.154a60` and `0.8.3-beta.56735f`, both are affected. running on a wheezy-based raspbian on a raspberry pi 2 with LANG=`de_DE.UTF-8`. 

reproduction steps:
(enable german locale with `dpkg-reconfigure locales`)

```
LANG=de_DE.UTF-8 info-beamer package-shader-example/
```

expected result: shader based animation is displayed
actual result: image ist displayed, but no animation

suspected cause (since there is no source code): with a german localisation floats which are converted to strings are formatted as `%d,%d` instead of `%d.%d`. this does confuse code which expects `%d.%d` formatted strings to be used as floats.

**Comment by dividuum** [comment] 2015-04-13 17:23
Lua documentation lied to me: According to the documentation, lua_objlen ''Returns the "length" of the value at the given acceptable index: for strings, this is the string length; for tables, this is the result of the length operator ('#'); for userdata, this is the size of the block of memory allocated for the userdata; for other values, it is 0.''

According to the documentation it seems like calling lua_objlen on a number returns 0. Instead the number (and its stack slot) is converted to a string (using locale rules) and its length is returned. Since this changes the stack slot from a number to a string object the following tonumber fails since it's unable to parse the just converted string. Fixed in the next release of info-beamer.

**Closed as completed by dividuum** 2015-04-13 17:23 UTC

**Comment by yetzt** [comment] 2015-04-13 17:32
yay, thanks.

**Comment by dividuum** [comment] 2015-04-13 17:36
Seems like it's been unspecified behaviour for quite some time: http://lua-users.org/lists/lua-l/2006-11/msg00355.html

**Comment by dividuum** [comment] 2015-04-13 20:31
Fixed in 0.9.0-pre2 (https://info-beamer.com/download/player#prerelease)

**Comment by yetzt** [comment] 2015-04-14 10:11
👍

**Comment by MichaelKreil** [comment] 2015-04-14 11:19
👍 Thanks!
